version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"

  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "main"
    labels:
      - "dependency-update"
    schedule:
      interval: "monthly"